on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Use Node 21.x
      uses: actions/setup-node@v5
      with:
        node-version: '21.x'

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm test
